extends: 'eslint:recommended'
parser: babel-eslint
plugins:
  - babel
  - mozilla

rules:
  consistent-return: [2]
  eqeqeq: [2]
  semi: [2, always]

  babel/array-bracket-spacing: [1]
  babel/generator-star-spacing: [1]
  babel/new-cap: [1]
  babel/no-await-in-loop: [1]
  babel/object-curly-spacing: [1]
  comma-dangle: [1, 'always-multiline']
  indent: [1, 2, {SwitchCase: 1}]
  linebreak-style: [1, unix]
  mozilla/balanced-listeners: [1]
  mozilla/no-aArgs: [1]
  mozilla/this-top-level-scope: [1]
  no-console: [1]
  no-unused-vars: [1]
  quotes: [1, 'single', 'avoid-escape']

  strict: [0]

env:
  es6: true
globals:
  require: false
  exports: true
  uneval: false
