actions:
  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude: "docs/"
  eslint:
    run: eslint {files}
    include:
      - "*.js"
      - "*.jsx"
    exclude:
      - ".eslintrc.js"
  stylelint:
    run: stylelint {files}
    include:
      - "*.css"
      - "*.scss"
