version: '2'

services:
  database:
    image: postgres:9.5.2

  normandy:
    image: mozilla/normandy
    links:
      - database
    environment:
      DJANGO_CONFIGURATION: ProductionInsecure
      DATABASE_URL: "postgres://postgres@database/postgres"

  proxy:
    image: nginx:1.9.14
    ports:
      - "8000:8000"
      - "8443:8443"
    links:
      - normandy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
